import { tokens } from '../../../SharedTool/style/tokens.shared.style';

export const sqlStyles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 16,
    width: '100%',
    maxWidth: 1060,
    margin: '0 auto',
    padding: '24px 22px 40px',
  },
  header: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  title: {
    margin: 0,
    fontSize: 22,
    letterSpacing: -0.3,
    color: tokens.colors.textMain,
    fontWeight: 800,
  },
  subtitle: {
    margin: 0,
    color: tokens.colors.textMuted,
    fontSize: 13,
    lineHeight: 1.4,
  },
  card: {
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 18,
    padding: 18,
    boxShadow: '0 18px 60px rgba(0,0,0,0.35)',
    backdropFilter: 'blur(14px)',
  },
  row: {
    display: 'flex',
    gap: 12,
    flexWrap: 'wrap' as const,
    alignItems: 'center',
  },
  fileInput: {
    display: 'block',
    width: '100%',
    padding: 12,
    borderRadius: 12,
    border: '1px dashed rgba(255,255,255,0.18)',
    background: 'rgba(0,0,0,0.22)',
    color: tokens.colors.textMain,
  },
  button: (accent: string, disabled?: boolean) => ({
    border: 'none',
    cursor: disabled ? 'not-allowed' : 'pointer',
    padding: '10px 14px',
    borderRadius: 12,
    fontWeight: 800,
    fontSize: 12,
    letterSpacing: 0.4,
    background: disabled ? 'rgba(255,255,255,0.06)' : accent,
    color: disabled ? 'rgba(255,255,255,0.55)' : '#071016',
    boxShadow: disabled ? 'none' : `0 16px 36px ${accent}33`,
    transition: 'transform 0.15s ease, filter 0.15s ease',
  }),
  badge: (accent: string) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 10px',
    borderRadius: 999,
    background: `${accent}22`,
    border: `1px solid ${accent}2c`,
    color: tokens.colors.textMain,
    fontSize: 12,
    fontWeight: 700,
  }),
  modelList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 10,
    marginTop: 12,
  },
  modelRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 12,
    padding: 12,
    borderRadius: 14,
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.18)',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  modelName: {
    fontSize: 14,
    fontWeight: 900,
    color: tokens.colors.textMain,
    margin: 0,
  },
  modelMeta: {
    fontSize: 12,
    color: tokens.colors.textMuted,
    marginTop: 4,
  },
  inputs: {
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap' as const,
  },
  inputBox: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    minWidth: 112,
  },
  label: {
    fontSize: 11,
    fontWeight: 800,
    color: 'rgba(255,255,255,0.72)',
    letterSpacing: 0.2,
  },
  number: {
    width: 120,
    padding: '10px 10px',
    borderRadius: 12,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(0,0,0,0.26)',
    color: tokens.colors.textMain,
    outline: 'none',
    fontWeight: 700,
  },
  error: {
    color: tokens.colors.accentError,
    fontSize: 12,
    marginTop: 10,
    whiteSpace: 'pre-wrap' as const,
  },
  hint: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
  },
};
