import React from 'react';
import { tokens } from '../../../../../SharedTool/style/tokens.shared.style';

export const endpointMonitorStyles = {
  card: {
    background: 'linear-gradient(180deg, rgba(14,18,26,0.92), rgba(8,10,16,0.95))',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: '24px',
    padding: '18px',
    boxShadow: '0 24px 80px rgba(0,0,0,0.35)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '14px',
  } as React.CSSProperties,
  topRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    flexWrap: 'wrap' as const,
  } as React.CSSProperties,
  titleWrap: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  } as React.CSSProperties,
  title: {
    margin: 0,
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: 'rgba(255,255,255,0.9)',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  subtitle: {
    margin: 0,
    fontSize: '12px',
    color: 'rgba(255,255,255,0.52)',
    lineHeight: 1.4,
  } as React.CSSProperties,
  importBadge: {
    padding: '6px 10px',
    borderRadius: '999px',
    background: 'rgba(37, 211, 102, 0.12)',
    border: '1px solid rgba(37, 211, 102, 0.25)',
    color: tokens.colors.accentGreen,
    fontSize: '11px',
    fontWeight: 800,
  } as React.CSSProperties,
  layout: {
    display: 'grid',
    gridTemplateColumns: 'minmax(280px, 360px) 1fr',
    gap: '14px',
    alignItems: 'start',
  } as React.CSSProperties,
  section: {
    background: 'rgba(255,255,255,0.025)',
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: '18px',
    padding: '14px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  } as React.CSSProperties,
  sectionTitle: {
    margin: 0,
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.12em',
    color: 'rgba(255,255,255,0.4)',
    textTransform: 'uppercase' as const,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  } as React.CSSProperties,
  fieldGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 112px',
    gap: '10px',
  } as React.CSSProperties,
  fieldLabel: {
    fontSize: '10px',
    fontWeight: 900,
    color: 'rgba(255,255,255,0.44)',
    textTransform: 'uppercase' as const,
    display: 'block',
    marginBottom: '6px',
    letterSpacing: '0.08em',
  } as React.CSSProperties,
  input: {
    width: '100%',
    borderRadius: '12px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.24)',
    color: 'rgba(255,255,255,0.88)',
    padding: '10px 12px',
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    outline: 'none',
    boxSizing: 'border-box' as const,
  } as React.CSSProperties,
  textarea: {
    width: '100%',
    minHeight: '88px',
    borderRadius: '14px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.24)',
    color: 'rgba(255,255,255,0.88)',
    padding: '10px 12px',
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    outline: 'none',
    boxSizing: 'border-box' as const,
    resize: 'vertical' as const,
  } as React.CSSProperties,
  actionRow: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap' as const,
  } as React.CSSProperties,
  primaryButton: {
    border: 'none',
    borderRadius: '12px',
    padding: '10px 14px',
    background: tokens.colors.accentTeal,
    color: '#041013',
    cursor: 'pointer',
    fontWeight: 900,
    fontSize: '11px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  secondaryButton: {
    borderRadius: '12px',
    padding: '10px 14px',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.08)',
    color: 'rgba(255,255,255,0.82)',
    cursor: 'pointer',
    fontWeight: 800,
    fontSize: '11px',
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  errorText: {
    color: tokens.colors.accentError,
    fontSize: '11px',
    margin: 0,
  } as React.CSSProperties,
  candidateList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    maxHeight: '216px',
    overflowY: 'auto' as const,
  } as React.CSSProperties,
  candidateRow: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    gap: '10px',
    alignItems: 'center',
    padding: '10px 12px',
    borderRadius: '14px',
    background: 'rgba(255,255,255,0.03)',
    border: '1px solid rgba(255,255,255,0.05)',
  } as React.CSSProperties,
  candidateLabel: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    minWidth: 0,
  } as React.CSSProperties,
  candidateTitle: {
    fontSize: '12px',
    fontWeight: 800,
    color: 'rgba(255,255,255,0.9)',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis' as const,
  } as React.CSSProperties,
  candidateMeta: {
    fontSize: '10px',
    color: 'rgba(255,255,255,0.45)',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis' as const,
  } as React.CSSProperties,
  tableWrap: {
    overflowX: 'auto' as const,
  } as React.CSSProperties,
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '12px',
  } as React.CSSProperties,
  th: {
    textAlign: 'left' as const,
    padding: '10px 8px',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    color: 'rgba(255,255,255,0.34)',
    fontSize: '10px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  td: {
    padding: '12px 8px',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
    color: 'rgba(255,255,255,0.84)',
    verticalAlign: 'top' as const,
  } as React.CSSProperties,
  urlCell: {
    maxWidth: '320px',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden' as const,
    textOverflow: 'ellipsis' as const,
  } as React.CSSProperties,
  miniButton: {
    borderRadius: '10px',
    border: '1px solid rgba(255,255,255,0.08)',
    padding: '7px 10px',
    background: 'rgba(255,255,255,0.04)',
    color: 'rgba(255,255,255,0.82)',
    cursor: 'pointer',
    fontSize: '10px',
    fontWeight: 800,
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  statusBadge: (status: 'pending' | 'ok' | 'error') =>
    ({
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '5px 9px',
      borderRadius: '999px',
      fontSize: '10px',
      fontWeight: 900,
      background:
        status === 'ok'
          ? 'rgba(37, 211, 102, 0.15)'
          : status === 'error'
            ? 'rgba(255, 82, 82, 0.16)'
            : 'rgba(255, 193, 7, 0.18)',
      color:
        status === 'ok'
          ? tokens.colors.accentGreen
          : status === 'error'
            ? tokens.colors.accentError
            : '#f7c55b',
    }) as React.CSSProperties,
  alertsPanel: {
    maxHeight: '220px',
    overflowY: 'auto' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  } as React.CSSProperties,
  alertItem: {
    padding: '10px 12px',
    borderRadius: '12px',
    background: 'rgba(255, 193, 7, 0.11)',
    border: '1px solid rgba(255, 193, 7, 0.18)',
    color: '#f6d98a',
    fontSize: '11px',
    fontFamily: "'JetBrains Mono', monospace",
    lineHeight: 1.45,
  } as React.CSSProperties,
  emptyState: {
    margin: 0,
    color: 'rgba(255,255,255,0.45)',
    fontSize: '12px',
    lineHeight: 1.5,
  } as React.CSSProperties,
};
