import React from 'react';
import { tokens } from '../../../../../SharedTool/style/tokens.shared.style';

export const styles = {
  container: {
    background: 'linear-gradient(180deg, rgba(14,18,26,0.92), rgba(8,10,16,0.95))',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: '24px',
    padding: '18px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '14px',
    boxShadow: '0 24px 80px rgba(0,0,0,0.35)',
  } as React.CSSProperties,
  title: {
    margin: 0,
    fontSize: '14px',
    fontWeight: 900,
    letterSpacing: '0.08em',
    color: 'rgba(255,255,255,0.92)',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  subtitle: {
    margin: 0,
    fontSize: '12px',
    color: 'rgba(255,255,255,0.55)',
    lineHeight: 1.4,
  } as React.CSSProperties,
  section: {
    marginBottom: '0',
    padding: '14px',
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: '18px',
    background: 'rgba(255,255,255,0.025)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  } as React.CSSProperties,
  sectionTitle: {
    margin: 0,
    fontSize: '11px',
    fontWeight: 900,
    letterSpacing: '0.12em',
    color: 'rgba(255,255,255,0.4)',
    textTransform: 'uppercase' as const,
  } as React.CSSProperties,
  helper: {
    fontSize: '11px',
    color: tokens.colors.accentTeal,
    fontWeight: 700,
  } as React.CSSProperties,
  helperMuted: {
    fontSize: '11px',
    color: 'rgba(255,255,255,0.5)',
    lineHeight: 1.5,
  } as React.CSSProperties,
  configGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
  } as React.CSSProperties,
  row: {
    display: 'grid',
    gridTemplateColumns: '88px 1.4fr 1fr 1fr auto',
    gap: '10px',
    alignItems: 'start',
  } as React.CSSProperties,
  input: {
    padding: '10px 12px',
    borderRadius: '12px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.24)',
    color: 'rgba(255,255,255,0.88)',
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    boxSizing: 'border-box' as const,
    width: '100%',
    outline: 'none',
  } as React.CSSProperties,
  select: {
    padding: '10px 12px',
    borderRadius: '12px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.24)',
    color: 'rgba(255,255,255,0.88)',
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    outline: 'none',
  } as React.CSSProperties,
  textarea: {
    padding: '10px 12px',
    borderRadius: '12px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(0,0,0,0.24)',
    color: 'rgba(255,255,255,0.88)',
    fontSize: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    outline: 'none',
    minHeight: '74px',
    resize: 'vertical' as const,
    width: '100%',
    boxSizing: 'border-box' as const,
  } as React.CSSProperties,
  buttonPrimary: {
    padding: '10px 15px',
    background: tokens.colors.accentTeal,
    color: '#071417',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    fontWeight: 900,
    fontSize: '11px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
  } as React.CSSProperties,
  buttonSuccess: {
    padding: '10px 15px',
    background: tokens.colors.accentGreen,
    color: '#071417',
    border: 'none',
    borderRadius: '12px',
    cursor: 'pointer',
    fontWeight: 900,
    fontSize: '11px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
  } as React.CSSProperties,
  buttonDanger: {
    padding: '10px 12px',
    background: 'rgba(255,82,82,0.16)',
    color: tokens.colors.accentError,
    border: '1px solid rgba(255,82,82,0.24)',
    borderRadius: '12px',
    cursor: 'pointer',
    fontWeight: 900,
  } as React.CSSProperties,
  resultItem: {
    padding: '10px 12px',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
    display: 'grid',
    gridTemplateColumns: '1.5fr 90px 160px',
    gap: '12px',
    alignItems: 'center',
    fontSize: '12px',
  } as React.CSSProperties,
  statusOk: {
    color: tokens.colors.accentGreen,
    fontWeight: 'bold',
  } as React.CSSProperties,
  statusError: {
    color: tokens.colors.accentError,
    fontWeight: 'bold',
  } as React.CSSProperties,
  actionsRow: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap' as const,
  } as React.CSSProperties,
  inlineActionsRow: {
    display: 'flex',
    gap: '10px',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
  } as React.CSSProperties,
};
