const { normalizeColumnName } = require('./utils');

const escapeCsv = (value) => {
  if (value === null || value === undefined) return '';
  const text = typeof value === 'object' ? JSON.stringify(value) : String(value);
  if (/[,"\n]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
  return text;
};

const toCsv = ({ rows, columns }) => {
  const headers = (columns || []).map((col) => normalizeColumnName(col));
  const lines = [headers.join(',')];
  (rows || []).forEach((row) => {
    lines.push(headers.map((col) => escapeCsv(row?.[col])).join(','));
  });
  return lines.join('\n');
};

const escapeSqlString = (value) => String(value ?? '').replace(/'/g, "''");

const sqlTypeMap = {
  INT: 'INTEGER',
  DECIMAL: 'NUMERIC(18,6)',
  BOOLEAN: 'BOOLEAN',
  TIMESTAMP: 'TIMESTAMP',
  JSON: 'JSONB',
  TEXT: 'TEXT',
};

const toSqlLiteral = (value, type) => {
  if (value === null || value === undefined) return 'NULL';
  const normalizedType = String(type || 'TEXT').toUpperCase();
  if (normalizedType === 'BOOLEAN') return value ? 'TRUE' : 'FALSE';
  if (normalizedType === 'INT' || normalizedType === 'DECIMAL') return Number(value);
  if (normalizedType === 'JSON') return `'${escapeSqlString(JSON.stringify(value))}'::jsonb`;
  return `'${escapeSqlString(value)}'`;
};

const toSql = ({ tableName, rows, columns, types }) => {
  const safeTable = normalizeColumnName(tableName || 'imported_data');
  const safeColumns = (columns || []).map((col) => normalizeColumnName(col));
  const createColumns = safeColumns.map((col) => {
    const kind = sqlTypeMap[String(types?.[col] || 'TEXT').toUpperCase()] || 'TEXT';
    return `  "${col}" ${kind}`;
  });

  let script = `CREATE TABLE IF NOT EXISTS "${safeTable}" (\n${createColumns.join(',\n')}\n);\n\n`;
  (rows || []).forEach((row) => {
    const values = safeColumns.map((col) => toSqlLiteral(row?.[col], types?.[col]));
    script += `INSERT INTO "${safeTable}" (${safeColumns.map((col) => `"${col}"`).join(', ')}) VALUES (${values.join(', ')});\n`;
  });
  return script;
};

const toPrismaMigrationSql = ({ tableName, rows, columns, types }) => {
  const safeTable = normalizeColumnName(tableName || 'imported_data');
  const base = toSql({ tableName: safeTable, rows, columns, types });
  return `-- Prisma migration-compatible SQL\n-- Generated by ViankoDataMigrator\n\n${base}`;
};

const exportDataset = ({ format, dataset }) => {
  const normalizedFormat = String(format || '').toLowerCase();
  if (normalizedFormat === 'json') {
    return {
      content: JSON.stringify(dataset.rows || [], null, 2),
      mimeType: 'application/json',
      extension: 'json',
    };
  }
  if (normalizedFormat === 'csv') {
    return {
      content: toCsv(dataset),
      mimeType: 'text/csv',
      extension: 'csv',
    };
  }
  if (normalizedFormat === 'sql') {
    return {
      content: toSql(dataset),
      mimeType: 'text/sql',
      extension: 'sql',
    };
  }
  if (normalizedFormat === 'prisma-migration') {
    return {
      content: toPrismaMigrationSql(dataset),
      mimeType: 'text/sql',
      extension: 'sql',
    };
  }
  throw new Error(`Formato de salida no soportado: ${format}`);
};

module.exports = {
  exportDataset,
};
