import type { CSSProperties } from 'react';
import { tokens } from '../../../../../SharedTool/style/tokens.shared.style';

export const dataMigratorStyles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  } as CSSProperties,
  helper: {
    margin: 0,
    fontSize: '11px',
    lineHeight: 1.6,
    color: 'rgba(255,255,255,0.68)',
  } as CSSProperties,
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    background: 'rgba(255,255,255,0.02)',
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: '14px',
    padding: '12px',
  } as CSSProperties,
  row: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
  } as CSSProperties,
  label: {
    fontSize: '10px',
    fontWeight: 900,
    color: 'rgba(255,255,255,0.45)',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  } as CSSProperties,
  input: {
    background: 'rgba(0,0,0,0.2)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '10px',
    padding: '8px 10px',
    color: 'white',
    fontSize: '12px',
    width: '100%',
    boxSizing: 'border-box',
  } as CSSProperties,
  textarea: {
    background: '#090d14',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '10px',
    padding: '10px',
    color: 'white',
    fontSize: '11px',
    minHeight: '150px',
    fontFamily: "'JetBrains Mono', monospace",
    resize: 'vertical',
  } as CSSProperties,
  buttonRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  } as CSSProperties,
  buttonPrimary: {
    border: 'none',
    borderRadius: '10px',
    background: tokens.colors.accentBlue,
    color: '#09121d',
    fontWeight: 900,
    fontSize: '10px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    padding: '9px 12px',
    cursor: 'pointer',
  } as CSSProperties,
  buttonSecondary: {
    border: '1px solid rgba(255,255,255,0.14)',
    borderRadius: '10px',
    background: 'rgba(255,255,255,0.02)',
    color: 'white',
    fontWeight: 800,
    fontSize: '10px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    padding: '9px 12px',
    cursor: 'pointer',
  } as CSSProperties,
  statusOk: {
    color: tokens.colors.accentGreen,
    fontSize: '11px',
    fontWeight: 700,
  } as CSSProperties,
  statusError: {
    color: tokens.colors.accentError,
    fontSize: '11px',
    fontWeight: 700,
  } as CSSProperties,
  chips: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  } as CSSProperties,
  chip: {
    padding: '4px 8px',
    borderRadius: '999px',
    border: `1px solid ${tokens.colors.accentTeal}33`,
    background: `${tokens.colors.accentTeal}12`,
    color: tokens.colors.accentTeal,
    fontSize: '10px',
    fontWeight: 800,
  } as CSSProperties,
} as const;
