import type { CSSProperties } from 'react';
import { tokens } from '../../../../../SharedTool/style/tokens.shared.style';

export const dataMigratorStyles = {
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  } as CSSProperties,
  helper: {
    margin: 0,
    fontSize: '11px',
    lineHeight: 1.6,
    color: 'rgba(255,255,255,0.68)',
  } as CSSProperties,
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    background: 'rgba(255,255,255,0.02)',
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: '14px',
    padding: '12px',
  } as CSSProperties,
  row: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
  } as CSSProperties,
  label: {
    fontSize: '10px',
    fontWeight: 900,
    color: 'rgba(255,255,255,0.45)',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  } as CSSProperties,
  input: {
    background: 'rgba(0,0,0,0.2)',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '10px',
    padding: '8px 10px',
    color: 'white',
    fontSize: '12px',
    width: '100%',
    boxSizing: 'border-box',
  } as CSSProperties,
  textarea: {
    background: '#090d14',
    border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: '10px',
    padding: '10px',
    color: 'white',
    fontSize: '11px',
    minHeight: '150px',
    fontFamily: "'JetBrains Mono', monospace",
    resize: 'vertical',
  } as CSSProperties,
  buttonRow: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
  } as CSSProperties,
  buttonPrimary: {
    border: 'none',
    borderRadius: '10px',
    background: tokens.colors.accentBlue,
    color: '#09121d',
    fontWeight: 900,
    fontSize: '10px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    padding: '9px 12px',
    cursor: 'pointer',
  } as CSSProperties,
  buttonSecondary: {
    border: '1px solid rgba(255,255,255,0.14)',
    borderRadius: '10px',
    background: 'rgba(255,255,255,0.02)',
    color: 'white',
    fontWeight: 800,
    fontSize: '10px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    padding: '9px 12px',
    cursor: 'pointer',
  } as CSSProperties,
  statusOk: {
    color: tokens.colors.accentGreen,
    fontSize: '11px',
    fontWeight: 700,
  } as CSSProperties,
  statusError: {
    color: tokens.colors.accentError,
    fontSize: '11px',
    fontWeight: 700,
  } as CSSProperties,
  chips: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
  } as CSSProperties,
  chip: {
    padding: '4px 8px',
    borderRadius: '999px',
    border: `1px solid ${tokens.colors.accentTeal}33`,
    background: `${tokens.colors.accentTeal}12`,
    color: tokens.colors.accentTeal,
    fontSize: '10px',
    fontWeight: 800,
  } as CSSProperties,
  predictionGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(240px, 0.85fr) minmax(320px, 1.15fr)',
    gap: '12px',
    alignItems: 'stretch',
  } as CSSProperties,
  predictionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '12px',
    flexWrap: 'wrap',
  } as CSSProperties,
  predictionTextPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    borderRadius: '14px',
    border: '1px solid rgba(255,255,255,0.06)',
    background: 'rgba(255,255,255,0.025)',
    padding: '10px',
    minHeight: '180px',
  } as CSSProperties,
  predictionText: {
    margin: 0,
    color: 'rgba(255,255,255,0.74)',
    fontSize: '11px',
    lineHeight: 1.6,
  } as CSSProperties,
  tableScroll: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    maxHeight: '360px',
    overflowY: 'auto',
    paddingRight: '6px',
  } as CSSProperties,
  tableAccordion: {
    border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: '14px',
    background: '#080f18',
    overflow: 'hidden',
  } as CSSProperties,
  tableSummary: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '10px 12px',
    cursor: 'pointer',
    color: 'white',
    fontSize: '12px',
    fontWeight: 900,
  } as CSSProperties,
  tableName: {
    color: 'rgba(255,255,255,0.46)',
    fontSize: '10px',
    fontWeight: 800,
  } as CSSProperties,
  tableScore: {
    color: tokens.colors.accentTeal,
    fontSize: '10px',
    fontWeight: 900,
    whiteSpace: 'nowrap',
  } as CSSProperties,
  tableActions: {
    display: 'flex',
    gap: '8px',
    padding: '0 10px 8px 10px',
  } as CSSProperties,
  tableActionButton: {
    border: `1px solid ${tokens.colors.accentTeal}33`,
    background: `${tokens.colors.accentTeal}12`,
    color: tokens.colors.accentTeal,
    borderRadius: '999px',
    padding: '6px 9px',
    cursor: 'pointer',
    fontSize: '9px',
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
  } as CSSProperties,
  fieldList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))',
    gap: '6px',
    padding: '0 10px 10px 10px',
  } as CSSProperties,
  fieldRow: {
    display: 'grid',
    gridTemplateColumns: '18px minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: '6px',
    border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: '10px',
    background: 'rgba(255,255,255,0.025)',
    padding: '7px 8px',
    cursor: 'pointer',
  } as CSSProperties,
  fieldRowSelected: {
    display: 'grid',
    gridTemplateColumns: '18px minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: '6px',
    border: `1px solid ${tokens.colors.accentBlue}55`,
    borderRadius: '10px',
    background: `${tokens.colors.accentBlue}12`,
    padding: '7px 8px',
    cursor: 'pointer',
  } as CSSProperties,
  fieldName: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: '11px',
    fontWeight: 800,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as CSSProperties,
  fieldType: {
    color: 'rgba(255,255,255,0.42)',
    fontSize: '9px',
    fontWeight: 900,
    textTransform: 'uppercase',
  } as CSSProperties,
  matchBadge: {
    borderRadius: '999px',
    padding: '2px 6px',
    background: `${tokens.colors.accentGreen}18`,
    color: tokens.colors.accentGreen,
    fontSize: '8px',
    fontWeight: 900,
    textTransform: 'uppercase',
  } as CSSProperties,
  graphToolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '10px',
    flexWrap: 'wrap',
  } as CSSProperties,
  graphLegend: {
    color: 'rgba(255,255,255,0.58)',
    fontSize: '10px',
    fontWeight: 700,
  } as CSSProperties,
  graphCanvas: {
    height: '520px',
    minHeight: '360px',
    borderRadius: '14px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: '#08111c',
    overflow: 'hidden',
  } as CSSProperties,
  graphEmpty: {
    minHeight: '360px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'rgba(255,255,255,0.45)',
    fontSize: '12px',
    fontWeight: 800,
  } as CSSProperties,
  graphNodeSource: {
    width: '210px',
    borderRadius: '12px',
    padding: '10px 12px',
    border: `1px solid ${tokens.colors.accentTeal}66`,
    background: '#0b1b22',
    color: 'white',
    boxShadow: `0 10px 28px ${tokens.colors.accentTeal}10`,
  } as CSSProperties,
  graphNodeTarget: {
    width: '210px',
    borderRadius: '12px',
    padding: '10px 12px',
    border: `1px solid ${tokens.colors.accentBlue}66`,
    background: '#0a1626',
    color: 'white',
    boxShadow: `0 10px 28px ${tokens.colors.accentBlue}10`,
  } as CSSProperties,
  graphNodeTable: {
    width: '230px',
    borderRadius: '14px',
    padding: '12px 14px',
    border: `1px solid ${tokens.colors.accentPurple}77`,
    background: '#101425',
    color: 'white',
    cursor: 'pointer',
    boxShadow: `0 14px 34px ${tokens.colors.accentPurple}16`,
  } as CSSProperties,
  graphNodeSelected: {
    width: '210px',
    borderRadius: '12px',
    padding: '10px 12px',
    border: `1px solid ${tokens.colors.accentGreen}`,
    background: '#102015',
    color: 'white',
    boxShadow: `0 0 0 3px ${tokens.colors.accentGreen}22, 0 14px 34px ${tokens.colors.accentGreen}18`,
  } as CSSProperties,
  graphNodeKind: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: '9px',
    fontWeight: 900,
    letterSpacing: '1px',
    textTransform: 'uppercase',
  } as CSSProperties,
  graphNodeLabel: {
    marginTop: '4px',
    color: 'white',
    fontSize: '13px',
    fontWeight: 900,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as CSSProperties,
  graphNodeMeta: {
    marginTop: '3px',
    color: 'rgba(255,255,255,0.58)',
    fontSize: '10px',
    fontWeight: 700,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as CSSProperties,
  warningList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    border: '1px solid rgba(255,191,71,0.18)',
    background: 'rgba(255,191,71,0.08)',
    color: '#ffcf75',
    borderRadius: '12px',
    padding: '10px',
    fontSize: '11px',
    fontWeight: 700,
  } as CSSProperties,
  edgeEditor: {
    display: 'grid',
    gridTemplateColumns: 'minmax(160px, 0.8fr) minmax(220px, 1fr) minmax(160px, 1fr) auto',
    alignItems: 'center',
    gap: '8px',
    border: '1px solid rgba(255,255,255,0.08)',
    background: 'rgba(255,255,255,0.03)',
    borderRadius: '12px',
    padding: '10px',
  } as CSSProperties,
} as const;
